
name: Python Analytics CI

on:
  push:
    branches: [ci-cd]
    paths:
      - "python-analytics/**"
      - ".github/workflows/python-analytics.yml"
  pull_request:
    branches: [ci-cd]
    paths:
      - "python-analytics/**"

jobs:
  lint-and-analyze:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: python-analytics

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install ruff mypy bandit types-requests


      - name: Run Ruff (Linting)
        run: ruff check .

      - name: Run Mypy (Type Checking)
        run: mypy .

      - name: Run Bandit (Security Analysis)
        run: bandit -r .

